"""
Django settings for pyred project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path
from datetime import timedelta


# ------------------------------
# Quick-start development settings
# ------------------------------
SECRET_KEY = 'django-insecure-_3vxbtx+8s_=%xsj9rmv=y=1m-&ubrdi1+!vhtom1qu$@3jaxd'
DEBUG = True
ALLOWED_HOSTS = []

# ------------------------------
# Applications
# ------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "pyreddit",
    "corsheaders",
    "rest_framework",
    'rest_framework_simplejwt.token_blacklist',
    "posts",
    "django_vite",
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# ------------------------------
# REST Framework + JWT
# ------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAdminUser",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_SECURE": False,       # dev mode
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_SAMESITE": "Lax",
}

# ------------------------------
# Middleware
# ------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   
]

ROOT_URLCONF = 'pyred.urls'
# ------------------------------
# BASE_DIR should point to the folder containing manage.py
# ------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Frontend dist folder
FRONTEND_DIST = BASE_DIR / "frontend" / "web" / "dist"

# ------------------------------
# Templates
# ------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
            FRONTEND_DIST,  # Vite dist
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pyred.wsgi.application'

# ------------------------------
# Database
# ------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------
# Password validators
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# ------------------------------
# CORS + CSRF
# ------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    'http://localhost:8000',
    'http://localhost:8001',
    'http://localhost:4173'
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    'http://localhost:8000',
    'http://localhost:8001',
    'http://localhost:4173'
]

# ------------------------------
# Internationalization
# ------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Montreal'
USE_I18N = True
USE_TZ = True

# ------------------------------
# Static files
# ------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    FRONTEND_DIST,  # Vite build files
]

# ------------------------------
# Django Vite
# ------------------------------
DJANGO_VITE = {
    "default": {
        "dev_mode": True,
        "dev_server_host": "localhost",
        "dev_server_port": 5173,
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ------------------------------
# Static files (CSS, JS, Images)
# ------------------------------
STATIC_URL = "/static/"                     # URL path for static files
STATIC_ROOT = BASE_DIR / "staticfiles"      # Where `collectstatic` will put them in production

# Where Django looks for extra static files (like your Vite build)
STATICFILES_DIRS = [
    BASE_DIR / "frontend/web/dist",                          # apps/frontend/web/dist
]
