# Generated by Django 5.2.10 on 2026-03-22 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_subforum_post_content_markdown_reply_post_subforum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="posts.reply",
            ),
        ),
    ]
