# Generated by Django 5.2.10 on 2026-04-10 23:37

import re
from django.db import migrations, models


NSFW_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in [
        r"\bnsfw\b",
        r"\bporn(?:ography)?\b",
        r"\bxxx\b",
        r"\bnud(?:e|ity|es)\b",
        r"\bsex(?:ual)?\b",
        r"\bonlyfans\b",
        r"\bhentai\b",
        r"\bfetish\b",
    ]
]

SWEAR_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in [
        r"\bfuck(?:ing|ed|er|ers)?\b",
        r"\bshit(?:ty|ting)?\b",
        r"\bbitch(?:es)?\b",
        r"\basshole(?:s)?\b",
        r"\bbastard(?:s)?\b",
        r"\bdamn\b",
        r"\bcrap\b",
    ]
]


def backfill_post_content_flags(apps, _schema_editor):
    Post = apps.get_model("posts", "Post")

    for post in Post.objects.all().iterator():
        combined_text = " ".join(
            part
            for part in [post.title, post.content, post.content_markdown]
            if part
        )
        post.is_nsfw = any(pattern.search(combined_text) for pattern in NSFW_PATTERNS)
        post.has_swears = any(pattern.search(combined_text) for pattern in SWEAR_PATTERNS)
        post.save(update_fields=["is_nsfw", "has_swears"])


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_rename_name_subforum_title_subforum_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="has_swears",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_nsfw",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_post_content_flags, migrations.RunPython.noop),
    ]
